INSERT INTO countries (country_code, name) VALUES
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BR', 'Brazil'),
('CA', 'Canada'),
('CL', 'Chile'),
('CN', 'China'),
('CO', 'Colombia'),
('CR', 'Costa Rica'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czechia'),
('DK', 'Denmark'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('EE', 'Estonia'),
('FI', 'Finland'),
('FR', 'France'),
('DE', 'Germany'),
('GR', 'Greece'),
('GT', 'Guatemala'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IT', 'Italy'),
('JP', 'Japan'),
('MX', 'Mexico'),
('NO', 'Norway'),
('PA', 'Panama'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PL', 'Poland'),
('PT', 'Portugal'),
('RU', 'Russia'),
('SA', 'Saudi Arabia'),
('SG', 'Singapore'),
('ES', 'Spain'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('TR', 'Turkiye'),
('GB', 'United Kingdom'),
('US', 'United States of America'),
('UY', 'Uruguay'),
('VE', 'Venezuela'),
('VN', 'Vietnam'),
('ZW', 'Zimbabwe');