INSERT INTO currencies (currency_code, name) VALUES
('AFN', 'Afghani'),
('ALL', 'Lek'),
('DZD', 'Algerian Dinar'),
('EUR', 'Euro'),
('AOA', 'Kwanza'),
('ARS', 'Argentine Peso'),
('AMD', 'Armenian Dram'),
('AUD', 'Australian Dollar'),
('AZN', 'Azerbaijan Manat'),
('BSD', 'Bahamian Dollar'),
('BHD', 'Bahraini Dinar'),
('BDT', 'Taka'),
('BBD', 'Barbados Dollar'),
('BYN', 'Belarusian Ruble'),
('BZD', 'Belize Dollar'),
('XOF', 'CFA Franc BCEAO'),
('BTN', 'Ngultrum'),
('BOB', 'Boliviano'),
('BRL', 'Real'),
('BGN', 'Lev'),
('CAD', 'Canadian Dollar'),
('CLP', 'Chilean Peso'),
('CNY', 'Yuan Renminbi'),
('COP', 'Colombian Peso'),
('CRC', 'Costa Rican Colon'),
('CUP', 'Cuban Peso'),
('CZK', 'Czech Koruna'),
('DKK', 'Danish Krone'),
('DOP', 'Dominican Peso'),
('EGP', 'Egyptian Pound'),
('SVC', 'El Salvador Colon'),
('ETB', 'Ethiopian Birr'),
('GHS', 'Ghana Cedi'),
('GTQ', 'Quetzal'),
('HNL', 'Lempira'),
('HKD', 'Hong Kong Dollar'),
('HUF', 'Forint'),
('ISK', 'Iceland Krona'),
('INR', 'Indian Rupee'),
('IDR', 'Rupiah'),
('ILS', 'New Israeli Sheqel'),
('JMD', 'Jamaican Dollar'),
('JPY', 'Yen'),
('KES', 'Kenyan Shilling'),
('KRW', 'Won'),
('LBP', 'Lebanese Pound'),
('MYR', 'Malaysian Ringgit'),
('MXN', 'Mexican Peso'),
('MAD', 'Moroccan Dirham'),
('NZD', 'New Zealand Dollar'),
('NIO', 'Cordoba Oro'),
('NGN', 'Naira'),
('NOK', 'Norwegian Krone'),
('PKR', 'Pakistan Rupee'),
('PAB', 'Balboa'),
('PEN', 'Sol'),
('PHP', 'Philippine Peso'),
('PLN', 'Zloty'),
('QAR', 'Qatari Rial'),
('RUB', 'Russian Ruble'),
('SAR', 'Saudi Riyal'),
('SGD', 'Singapore Dollar'),
('ZAR', 'Rand'),
('CHF', 'Swiss Franc'),
('TWD', 'New Taiwan Dollar'),
('THB', 'Baht'),
('TRY', 'Turkish Lira'),
('GBP', 'Pound Sterling'),
('USD', 'US Dollar'),
('UYU', 'Peso Uruguayo'),
('VES', 'Bolívar Soberano'),
('VND', 'Dong'),
('ZWG', 'Zimbabwe Gold');